spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wcg_mall
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.qq.com
    port: 465
    username: 1774532899@qq.com
    password: matlgqstvuzzbjgg
    default-encoding: utf-8
    properties:
      mail:
        debug: true
        smtp:
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 管理端
      packages-to-scan:
        - com.chenweijiang.wcg_mall.controller.admin
    - group: 用户端
      packages-to-scan:
        - com.chenweijiang.wcg_mall.controller.user

mall:
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tQgLr4j7p69APt1LxKU
    access-key-secret: 1sALpOS7hbNyAEWJCXvIZlh2JiFdP5
    bucket-name: web-framework-cwj

  jwt:
    admin-secret-key: cwg.mall.admin
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization
    user-secret-key: cwg.mall.user
    user-ttl: 7200000
    user-token-name: Authorization


