server:
  #服务运行端口
  port: 1203
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  profiles:
    include: alipay
  #数据库配置
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    #redis配置
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
#邮件服务配置
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: utf-8
    properties:
      mail:
        debug: true
        smtp:
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
#Mybatis映射配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chenweijiang.wcg_mall.pojo
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: com.chenweijiang.wcg_mall.utils.SimpleMybatisLogger
    map-underscore-to-camel-case: true
# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#测试文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 管理端
      packages-to-scan:
        - com.chenweijiang.wcg_mall.controller.admin
    - group: 用户端
      packages-to-scan:
        - com.chenweijiang.wcg_mall.controller.user

mall:
  #阿里云oss配置
  alioss:
    endpoint: ${OSS_ENDPOINT}
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: ${OSS_BUCKET_NAME}
  #jwt配置
  jwt:
    #管理端jwt配置
    admin-secret-key: ${ADMIN_JWT_SECRET}
    admin-ttl: ${ADMIN_JWT_TTL}
    admin-token-name: Authorization
    #用户端jwt配置
    user-secret-key: ${USER_JWT_SECRET}
    user-ttl: ${USER_JWT_TTL}
    user-token-name: Authorization
  #支付配置
  alipay:
    app-id: ${ALIPAY_APP_ID}
    private-key: ${ALIPAY_PRIVATE_KEY}
    alipay-public-key: ${ALIPAY_PUBLIC_KEY}
    #notify-url的地址必须为外网可以访问的地址
    notify-url:  ${ALIPAY_NOTIFY_URL}
    #支付宝回调地址
    #return-url: http://localhost:5173/purchaseNotif
    charset: utf-8
    sign-type: RSA2
    #支付宝网关
    gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do

    format: json

